### ISSUE TITLE
Upsert & Update Switched

### ISSUE THREAD

**Issue by matiusmonkey** [geistinteractive/fms-xml-client#10]
Hi Todd,

Great work on this API by the way.

It looks to me when testing that the upsert and update functions are reversed, i.e. update will create a record if it doesn't exist and upsert will not.

**Comment by toddgeist** [comment]
Hi :-)

Thanks for taking the time to report an issue.

I just went and reviewed the code, hoping it was just a simple screw up. But the code looks good. And we have tests in place that would catch this.  So can you provide a test that shows the issue?  Or any sample code that shows it.

If you include a node script and a sample db, that would be enough.

Thanks again

**Comment by matiusmonkey** [comment]
Hi Todd,

Sorry for the late response.

Maybe I misunderstand how update and upsert should work, I've included an example, where if you run JPQuery.js with it, update will create a new record and upsert will change the data on the found query.

I'm running FMS 13 and node 7.4.0

[fms-xml-client.zip](https://github.com/geistinteractive/fms-xml-client/files/1280321/fms-xml-client.zip)

**Comment by toddgeist** [comment]
Thanks for that.  I found the issue with update.  I'll fix that.

`Upsert` is working correctly.  If it finds a record it will update it. If it doesn't find a record it will `insert` it

PS. Your test file had one of the fields set to a number type.  I thought that was the problem at first but apparently, the xml gateway doesn't care about that.
